using DotnetPkgsAiDocs.Analysis;

namespace DotnetPkgsAiDocs.Output;

/// <summary>
/// Generates Markdown output with embedded Mermaid diagrams for dependency graphs and public API surfaces.
/// </summary>
public static class MarkdownWriter
{
    public static void WriteDependencyGraph(
        string outputPath,
        IReadOnlyList<DependencyResult> results,
        IReadOnlyList<string> firstPartyPrefixes)
    {
        using var writer = new StreamWriter(outputPath);

        writer.WriteLine("# Transitive Dependency Graph");
        writer.WriteLine();
        writer.WriteLine("*Auto-generated by [dotnet-pkgs-ai-docs](https://github.com/jmprieur/pkgs-ai-docs)*");
        writer.WriteLine();
        writer.WriteLine("This file lists the **complete transitive dependency closure** for each package,");
        writer.WriteLine("computed from the actual `.nupkg` files. It is organized by package and target framework.");
        writer.WriteLine();

        // Group results by package
        var byPackage = results
            .GroupBy(r => r.PackageId, StringComparer.OrdinalIgnoreCase)
            .OrderBy(g => g.Key, StringComparer.OrdinalIgnoreCase);

        foreach (var pkgGroup in byPackage)
        {
            writer.WriteLine("---");
            writer.WriteLine();
            writer.WriteLine($"## {pkgGroup.Key}");
            writer.WriteLine();

            foreach (var result in pkgGroup.OrderBy(r => r.TargetFramework))
            {
                writer.WriteLine($"### {result.TargetFramework}");
                writer.WriteLine();

                // Mermaid diagram
                var mermaid = MermaidGenerator.GenerateDependencyGraph(result, firstPartyPrefixes);
                if (!string.IsNullOrEmpty(mermaid))
                {
                    writer.WriteLine("```mermaid");
                    writer.Write(mermaid);
                    writer.WriteLine("```");
                    writer.WriteLine();
                }

                // Classify dependencies
                var firstParty = result.Dependencies
                    .Where(d => IsFirstParty(d.Id, firstPartyPrefixes))
                    .ToList();

                var external = result.Dependencies
                    .Where(d => !IsFirstParty(d.Id, firstPartyPrefixes))
                    .ToList();

                if (firstPartyPrefixes.Count > 0 && firstParty.Count > 0)
                {
                    writer.WriteLine("**1P packages (version managed by metapackage):**");
                    foreach (var dep in firstParty)
                    {
                        writer.WriteLine($"- {dep.Id} >= {dep.ResolvedVersion}");
                    }
                    writer.WriteLine();
                }

                if (external.Count > 0)
                {
                    writer.WriteLine("**External packages (pulled in transitively):**");
                    foreach (var dep in external)
                    {
                        writer.WriteLine($"- {dep.Id} >= {dep.ResolvedVersion}");
                    }
                    writer.WriteLine();
                }

                if (result.Dependencies.Count == 0)
                {
                    writer.WriteLine("*No dependencies.*");
                    writer.WriteLine();
                }
            }
        }
    }

    public static void WritePublicApi(
        string outputPath,
        IReadOnlyList<PublicApiResult> results)
    {
        using var writer = new StreamWriter(outputPath);

        writer.WriteLine("# Public API Surface");
        writer.WriteLine();
        writer.WriteLine("*Auto-generated by [dotnet-pkgs-ai-docs](https://github.com/jmprieur/pkgs-ai-docs)*");
        writer.WriteLine();
        writer.WriteLine("This file lists every public type and member for each package and target framework.");
        writer.WriteLine("Format follows Roslyn's `PublicAPI.Shipped.txt` convention.");
        writer.WriteLine();

        var byPackage = results
            .GroupBy(r => r.PackageId, StringComparer.OrdinalIgnoreCase)
            .OrderBy(g => g.Key, StringComparer.OrdinalIgnoreCase);

        foreach (var pkgGroup in byPackage)
        {
            writer.WriteLine("---");
            writer.WriteLine();

            var firstResult = pkgGroup.First();
            writer.WriteLine($"## {pkgGroup.Key} {firstResult.PackageVersion}");
            writer.WriteLine();

            foreach (var result in pkgGroup.OrderBy(r => r.TargetFramework))
            {
                writer.WriteLine($"### {result.TargetFramework}");
                writer.WriteLine();

                if (result.ApiLines.Count == 0)
                {
                    writer.WriteLine("*No public API found.*");
                }
                else
                {
                    writer.WriteLine("```");
                    foreach (var line in result.ApiLines)
                    {
                        writer.WriteLine(line);
                    }
                    writer.WriteLine("```");
                }
                writer.WriteLine();
            }
        }
    }

    private static bool IsFirstParty(string packageId, IReadOnlyList<string> prefixes)
    {
        return prefixes.Any(p => packageId.StartsWith(p, StringComparison.OrdinalIgnoreCase));
    }
}
